export default {
  colors: {
    background: '#0f0f0f',
    background_red: '#a20612',

    header: '#a20612',
    button: '#a20612',
    card: '#141414',
    cardRemove: '#a70713',
    favorite_border: '#343434',
    input_border: '#343434',

    text_white: '#000',
    text_gray: '#7B7B7B',
    text_dark: '#AdAdAd',
    text_red: '#C70d20',
    text_login: '#9B9B9B',
    text_light: '#f2f2f2',
    separator: '#333333',

    icon_gray: '#7B7B7B',
    icon_white: '#222222',
    icon_red: '#a20612',
    icon_dark: '#2B2B2E',
    icon_black: '#fff',
    icon_slider: '#C4C4C4',
    icon_light: '#f2f2f2',
    favorite_color: '#222222',
    line: '#222222',
    priceView: '#343434',

    modalBackGround: 'rgba(0, 0, 0, 0.5)',
    modalButtonClose: '#a20612',

    devsBanner: '#102844',
    theme_button: '#350887',
    theme_button_circle: '#0508a7',
  },

  barStyles: {
    dark: 'light-content',
    light: 'dark-content',
  },

  fonts: {
    primaryReg: 'Poppins-Regular',
    primaryMed: 'Poppins-Medium',

    secondaryReg: 'Archivo-Regular',
    secondaryMed: 'Archivo-Medium',
    secondaryBold: 'Archivo-Bold',
  },

  icons: {
    home: require('../assets/Icons/home.png'),
    favorite: require('../assets/Icons/favorite-dark.png'),
    deliverylist: require('../assets/Icons/deliverylist.png'),
    profile: require('../assets/Icons/profile.png'),
    email: require('../assets/loginIcons/E-mail.png'),
    password: require('../assets/loginIcons/Senha.png'),
    eye: require('../assets/loginIcons/eye.png'),
    arrow: require('../assets/loginIcons/Arrow.png'),
    woman: require('../assets/loginIcons/Woman.png'),
    womanleft: require('../assets/loginIcons/WomanLeft.png'),
    womanup: require('../assets/loginIcons/WomanUp.png'),
    cpf: require('../assets/loginIcons/Cpf.png'),
    phone: require('../assets/loginIcons/Cellphone.png'),
    name: require('../assets/loginIcons/Name.png'),
    locale: require('../assets/loginIcons/Locale.png'),
    exit: require('../assets/loginIcons/Exit.png'),
    womansuccess: require('../assets/loginIcons/womansuccess.png'),
    search: require('../assets/Icons/search.png'),
    iconLocale: require('../assets/Icons/locale.png'),
    favoriteRestaurant: require('../assets/Icons/favorite-dark.png'),
    starRatio: require('../assets/Icons/star.png'),
    add: require('../assets/Icons/add.png'),
    remove: require('../assets/Icons/remove.png'),
    litter: require('../assets/Icons/litter.png'),
    hamper: require('../assets/Icons/hamper.png'),
    itemsCircle: require('../assets/Icons/itemscircle.png'),
    exitWhite: require('../assets/Icons/exitwhite.png'),
    dollar: require('../assets/Icons/dollar.png'),
    cleanUp: require('../assets/Icons/cleanUp.png'),
    checkOrders: require('../assets/Icons/checkOrders.png'),
    map: require('../assets/Icons/map.png'),
    checkorder: require('../assets/Icons/checkorder.png'),
    deliveryorder: require('../assets/Icons/deliveryorder-dark.png'),
    doingorder: require('../assets/Icons/doingorder.png'),
    waitingorder: require('../assets/Icons/waitingorderdark.png'),
    editInfo: require('../assets/Icons/editInfo.png'),
    help: require('../assets/Icons/help.png'),
    settingsArrow: require('../assets/Icons/settingsArrow.png'),
    about: require('../assets/Icons/about.png'),
    logoutIcon: require('../assets/Icons/logoutIcon.png'),
    deleteUserIcon: require('../assets/Icons/deleteUserIcon.png'),
    restaurant: require('../assets/Icons/restaurant.png'),
    trash: require('../assets/Icons/trash.png'),
    camera: require('../assets/Icons/camera.png'),
    cleanEye: require('../assets/Icons/eye.png'),
    blankcircle: require('../assets/loginIcons/BlanckCircle-dark.png'),
    circle: require('../assets/loginIcons/Circle-dark.png'),
    check: require('../assets/loginIcons/Check-dark.png'),
    dark: require('../assets/themeIcons/dark.png'),
    light: require('../assets/themeIcons/light.png'),
    default: require('../assets/themeIcons/default.png'),
    coupon: require('../assets/Icons/coupon.png'),
  },

  images: {
    hamburger: require('../assets/loginImages/dark/null.png'),
    pizza: require('../assets/loginImages/dark/null.png'),
    footer: require('../assets/loginImages/dark/null.png'),
    develfood: require('../assets/loginImages/develfood.png'),
    banner: require('../assets/Images/banner.png'),
    noImage: require('../assets/Images/NoImage-dark.png'),
    pizzaImage: require('../assets/Images/pizza.png'),
    camaraoImage: require('../assets/Images/camarao.png'),
    notFound: require('../assets/Images/not_found-dark.png'),
    mapImage: require('../assets/Images/mapImage.png'),
    checkoutEmpty: require('../assets/Images/checkoutEmpty-dark.png'),
    checkoutSuccess: require('../assets/Images/checkoutsuccess-dark.png'),
    noOrder: require('../assets/Images/noOrder-dark.png'),
    waiting: require('../assets/Images/waiting.png'),
    doing: require('../assets/Images/doing.png'),
    inRoute: require('../assets/Images/inRoute.png'),
    delivered: require('../assets/Images/delivered.png'),
    noFavorites: require('../assets/Images/noFavorites-dark.png'),
    authEmail: require('../assets/RedefinePasswordImages/auth-email-dark.png'),
    forgotPassword: require('../assets/RedefinePasswordImages/forgot_password-dark.png'),
    lock: require('../assets/RedefinePasswordImages/lock-dark.png'),
    redefineSuccess: require('../assets/RedefinePasswordImages/redefine-success-dark.png'),
    pin: require('../assets/Images/pin.png'),
    eu: require('../assets/Images/Eu.jpeg'),
    logoutImage: require('../assets/Images/logoutImage-dark.png'),
    develFoodLogo: require('../assets/Images/Logo.png'),
    timeDevelFood: require('../assets/Images/TimeDevelfood.jpeg'),
    gustaGol: require('../assets/Images/gustaGol.jpeg'),
    isaias: require('../assets/Images/isaias.jpg'),
    kevinCareca: require('../assets/Images/kevinCareca.jpg'),
    manoela: require('../assets/Images/manoela.jpg'),
    carlaMelhorAgilista: require('../assets/Images/carlaMelhorAgilista.jpg'),
    michael: require('../assets/Images/michael.jpg'),
    star: require('../assets/Images/estrela.png'),
    starEmpty: require('../assets/Images/estrela_vazia.png'),
    error: require('../assets/Images/error.png'),
  },
};
