export default {
  colors: {
    background: '#FFFFFF',
    background_red: '#C20C18',

    header: '#C20C18',
    button: '#C20C18',
    card: '#F0F0F5',
    favorite_border: '#DEDCDC',

    text_white: '#FFFFFF',
    text_gray: '#BFBABA',
    text_dark: '#2B2B2E',
    text_login: '#68484A',

    icon_gray: '#BFBABA',
    icon_white: '#FFFFFF',
    icon_red: '#C20C18',
    icon_dark: '#2B2B2E',
  },

  fonts: {
    primaryReg: 'Poppins-Regular',
    primaryMed: 'Poppins-Medium',

    secondaryReg: 'Archivo-Regular',
    secondaryMed: 'Archivo-Medium',
    secondaryBold: 'Archivo-Bold',
  },

  icons: {
    home: require('../assets/Icons/home.png'),
    favorite: require('../assets/Icons/favorite.png'),
    deliverylist: require('../assets/Icons/deliverylist.png'),
    profile: require('../assets/Icons/profile.png'),
    email: require('../assets/loginIcons/E-mail.png'),
    password: require('../assets/loginIcons/Senha.png'),
    eye: require('../assets/loginIcons/eye.png'),
    arrow: require('../assets/loginIcons/Arrow.png'),
    circle: require('../assets/loginIcons/Circle.png'),
    blankcircle: require('../assets/loginIcons/BlanckCircle.png'),
    woman: require('../assets/loginIcons/Woman.png'),
    womanleft: require('../assets/loginIcons/WomanLeft.png'),
    check: require('../assets/loginIcons/Check.png'),
    womanup: require('../assets/loginIcons/WomanUp.png'),
    cpf: require('../assets/loginIcons/Cpf.png'),
    phone: require('../assets/loginIcons/Cellphone.png'),
    name: require('../assets/loginIcons/Name.png'),
    locale: require('../assets/loginIcons/Locale.png'),
    exit: require('../assets/loginIcons/Exit.png'),
    womansuccess: require('../assets/loginIcons/womansuccess.png'),
    search: require('../assets/Icons/search.png'),
    iconLocale: require('../assets/Icons/locale.png'),
    favoriteRestaurant: require('../assets/Icons/favoriteRestaurant.png'),
    starRatio: require('../assets/Icons/star.png'),
    add: require('../assets/Icons/add.png'),
    remove: require('../assets/Icons/remove.png'),
    litter: require('../assets/Icons/litter.png'),
    hamper: require('../assets/Icons/hamper.png'),
    itemsCircle: require('../assets/Icons/itemscircle.png'),
    exitWhite: require('../assets/Icons/exitwhite.png'),
    dollar: require('../assets/Icons/dollar.png'),
    cleanUp: require('../assets/Icons/cleanUp.png'),
    checkOrders: require('../assets/Icons/checkOrders.png'),
    map: require('../assets/Icons/map.png'),
  },

  images: {
    hamburger: require('../assets/loginImages/hamburger.png'),
    pizza: require('../assets/loginImages/metadepizza.png'),
    footer: require('../assets/loginImages/footer.png'),
    develfood: require('../assets/loginImages/develfood.png'),
    banner: require('../assets/Images/banner.png'),
    noImage: require('../assets/Images/NoImage.png'),
    pizzaImage: require('../assets/Images/pizza.png'),
    camaraoImage: require('../assets/Images/camarao.png'),
    notFound: require('../assets/Images/not_found.png'),
    mapImage: require('../assets/Images/mapImage.png'),
    checkoutEmpty: require('../assets/Images/checkoutEmpty.png'),
    checkoutSuccess: require('../assets/Images/checkoutsuccess.png'),
    noOrder: require('../assets/Images/noOrder.png'),
    waiting: require('../assets/Images/waiting.png'),
    doing: require('../assets/Images/doing.png'),
    inRoute: require('../assets/Images/inRoute.png'),
    delivered: require('../assets/Images/delivered.png'),
  },
};
